#!/bin/sh
#
# @name 3DR Iris Quadrotor SITL (6 depth camera)
#
# @type Quadrotor Wide
#

. ${R}etc/init.d-posix/airframes/10016_iris

# EKF2: Vision position and heading
param set-default EKF2_AID_MASK 24
param set-default EKF2_EV_DELAY 5

param set-default EKF2_HGT_MODE Vision
param set-default EKF2_MAG_TYPE None

